# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RegionDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for RegionDemo
pod 'HQDBDecode', :git => 'ssh://git@git.solot.co:10022/liuhuanqing/HQDBDecode.git'
pod 'YHLanguageSetting', :git => 'http://git.solot.co:10080/liao/YHLanguageSetting.git'
end
